version: "3.9"

networks:
  backend:

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - /var/lib/postgresql/data
    networks:
      - backend
  app:
    build:
      context: .
      args:
        DEPS: dev
    ports:
      - "8000:8000"
    environment:
      DEBUG: "true"
      DATABASE_USER: ${PG_USER}
      DATABASE_PASSWORD: ${PG_PASSWORD}
      DATABASE_DB: ${PG_DATABASE}
      DATABASE_HOST: postgres
    networks:
      - backend